# FastAPI Starter Quick Start Configuration File | FastAPI Starter 一键启动配置文件
# Integrated with PostgreSQL database, no need to install PostgreSQL locally | 集成了PostgreSQL数据库，无需本地安装PostgreSQL
#
# Common commands: | 常用命令:
# Quick start:       docker compose -f docker/docker-compose-quickstart.yml up -d | 一键启动:       docker compose -f docker/docker-compose-quickstart.yml up -d
# Stop all services: docker compose -f docker/docker-compose-quickstart.yml down | 停止所有服务:    docker compose -f docker/docker-compose-quickstart.yml down
# View logs:         docker compose -f docker/docker-compose-quickstart.yml logs -f | 查看日志:       docker compose -f docker/docker-compose-quickstart.yml logs -f
# Rebuild:           docker compose -f docker/docker-compose-quickstart.yml build | 重新构建:       docker compose -f docker/docker-compose-quickstart.yml build
#
# Complete rebuild: | 完全重建:
# docker compose -f docker/docker-compose-quickstart.yml down -v
# docker compose -f docker/docker-compose-quickstart.yml up -d

services:
  # PostgreSQL database service | PostgreSQL 数据库服务
  db:
    image: postgres:15-alpine
    container_name: lightning-fastapi-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lightning-fastapi
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # FastAPI application service | FastAPI 应用服务
  app:
    image: lightning-fastapi-dev:latest
    container_name: lightning-fastapi-dev
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../app:/WORKDIR/app
    env_file:
      - ../.env
    environment:
      # Override database connection settings in .env file, connect to Docker internal PostgreSQL | 覆盖.env文件中的数据库连接设置，连接到Docker内部的PostgreSQL
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lightning-fastapi
    depends_on:
      db:
        condition: service_healthy
    command: /WORKDIR/scripts/start.sh

volumes:
  postgres_data: 